### ISSUE TITLE
Disable NTFS file checking on Windows

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/SIMPL#101]
Qt's NTFS file checking is notoriously slow and buggy (see [here](http://doc.qt.io/qt-5/qfiledevice.html) for more details).  This makes preflights on Windows when a "Write DREAM3.D Data File" filter is in the pipeline very slow. 

To disable the file checking, add the following to the DREAM3D_SDK.cmake file

``set(SIMPL_ENABLE_NTFS_FILE_CHECKING "OFF" CACHE BOOL "" FORCE)``

**Comment by imikejackson** [comment]
Going to to just comment out the code that triggered the permissions check. If it does not work then we will just leave it out.
