### ISSUE TITLE
Saved Pipeline in HDF5 file does not represent to entire data processing history

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/SIMPL#16]
Previously, when the pipeline was saved into the output HDF5 .dream3d file, the entire processing history for the data was "saved", since any future processing that used that .dream3d would just append those filters to HDF5 group.  

The new way of storing the pipeline just stores the JSON information as one long string.  While more compact, this string is overwritten whenever the .dream3d file is used in another pipeline.  This is a critical problem, since all processing history for a given .dream3d is lost.

A possible solution is to create a new Pipeline HDF5 data string set within the Pipeline group whenever the .dream3d file is used in a pipeline.  This would also require naming the Pipeline string data sets with some numerical counter ("Pipeline_0, Pipeline_1" etc.).  Additionally, the functionality used to extract the saved pipelines out of the .dream3d file would have to allow for the option to choose which pipeline to extract, or to extract all of them appended to one another (which was the former behavior).

**Comment by imikejackson** [comment]
We should be able to append to the pipeline that is stored as JSON. Should be a matter of extracting the previous pipeline, appending the new pipeline, and saving the new larger pipeline back to the HDF5 file.

**Comment by sdonegan** [comment]
That works, then it would completely replicate the previous functionality.
