### ISSUE TITLE
SIMPLib dll does not get copied into the install location when making a package

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/SIMPL#20]
Tested on Windows; it seems that the SIMPLib.dll is not getting into the zipped package.  Most recent nightly build reflects this issue.

**Comment by sdonegan** [comment]
H5Support dll is also missing; it looks like the .lib files for both H5Support and SIMPLib were copied over instead of the DLLs.

**Comment by imikejackson** [comment]
fixed and closed with commit 2eb6b6daa788190a6bbe53c493c518770240a526
