### ISSUE TITLE
RotateSampleRefFrame allocates DataArrays in preflight

### ISSUE THREAD

**Issue by JDuffeyBQ** [BlueQuartzSoftware/SIMPL#427]
`RotateSampleRefFrame` resizes the cell attribute matrix of the image geometry to be rotated to that the correct dimensions are displayed. To do this it calls `AttributeMatrix::resizeAttributeArrays` which resizes the arrays in the attribute matrix even if the filter is in preflight not execute. This causes large memory use and longer preflight times with larger arrays.

**Comment by imikejackson** [comment]
closed by commit cc5fa4bc2
