### ISSUE TITLE
Deep copy functions for DataContainer, AttributeMatrix, and IGeometry should take a forceNoAllocate argument

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/SIMPL#48]
DataArray objects currently accept a forceNoAllocate argument on deepCopy(), which gives the option to avoid actually performing an allocation; this is useful if only a "shallow" version of the array is needed, i.e. when only the descriptive information of the array is desired for something like preflight.  DataContainers, AttributeMatrices, and IGeometry objects do not have this option, meaning that if one calls deepCopy() on a DataContainer, all DataArrays in that DataContainer end up being copied and allocated.  For consistency, add similar "forceNoAllocate" arguments to all the different data structure objects to allow "shallow" copies (the argument can take a default false, just like for DataArray).

**Comment by imikejackson** [comment]
Could you describe the technical difference between deep and shallow copy of a DataContainer? We were just messing around with these functions trying to come up with something easier to understand for developers

**Comment by sdonegan** [comment]
Current use case is calling a deepCopy() on a DataContainer during preflight.  This causes all the AttributeMatrices to deepCopy() themselves, which in turn calls deepCopy() on all the DataArrays.  By default, the arrays then allocate.  If the arrays happened to be large (as may be the case with geometry arrays), then you end up with a lot of allocation during preflight.

Avoiding allocation with a forceNoAllocate argument would allow all the descriptive information of the arrays to remain intact (for the data browser) without actually triggering an allocation.  The trick is then to pass into the deepCopy() function the negation of the return of the getInPreflight() function, so that the allocations only happen when dataCheck() is called during execute.

**Comment by imikejackson** [comment]
So really we need a deep copy and a shallow copy function? The deepCopy will make true copies of the underlying data arrays (what ever their state may be) where as a shallow copy will create a new reference to the underlying data arrays?

**Comment by sdonegan** [comment]
We could, but then you would have to call the correct function in preflight as opposed to execute (you couldn't do my getInPreflight() argument trick).  The specific use case I'm dealing with right now is a generic filter that copies any object.  Right now, the filter performs all its logic in the dataCheck() function, and calls deepCopy() like this:

``IDataArray::Pointer copy = someDataArray->deepCopy(!getInPreflight());
``

A shallowCopy() function works just as well, I'd just have to use that in dataCheck() and implement code in execute() that actually calls deepCopy().

**Comment by imikejackson** [comment]
Within preflight you would need something like:
`if(getInPreflight()) shallowCopy()
else
deepCopy()`

or do one in preflight and one in execute. I think having easier to read methods would make the use of the methods easier for developers. The current "forceNoAlloate" can be confusing since the value is in the negative.

**Comment by sdonegan** [comment]
That's reasonable; I'll open another issue to add shallowCopy() implementations and we can close #48, #46, and #47.
