### ISSUE TITLE
Implement shallowCopy() functions for DataContainer, AttributeMatrix, IDataArray, and IGeometry

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/SIMPL#49]
Currently, all these objects implement a deepCopy() function that (should) explicitly copy all contents into a new shared pointer instance (the IGeometry versions are bugged at the moment).  The IDataArray implementation allows the developer to avoid an allocation with a Boolean argument (a "shallow" copy), but the other objects do not.  This is useful when the descriptive information of the object is desired, but the developer wants to avoid allocating until later.

For clarity, implement shallowCopy() functions for all these objects and remove the deepCopy() argument in IDataArray.

**Comment by imikejackson** [comment]
More or less fixed by commit 6f207f8e0f707633fbceb57a751d8817bf9fabe0
