### ISSUE TITLE
Incorrect matrix inversion !!!

### ISSUE THREAD

**Issue by OndrejSedivy** [BlueQuartzSoftware/SIMPL#6]
The function MatrixMath::Invert3x3 behaves incorrectly as it always returns transposition of the correct result. For example, matrix (1,0,1,0,1,0,0,0,1) should be inverted as (1,0,-1,0,1,0,0,0,1), but the function returns (1,0,0,0,1,0,-1,0,1) (regardless whether the numbers are placed by rows or by columns).

**Comment by imikejackson** [comment]
Just to be clear the matrix:

1 0 1
0 1 0
0 0 1

should be inverted as:

1 0 -1
0 1 0
0 0 1

But the function returns:

1 0 0
0 1 0
-1 0 1

**Comment by OndrejSedivy** [comment]
yes, that's what I get

**Comment by imikejackson** [comment]
Found and fixed the issue. Please pull the latest updates to the repository and try your example again.

**Comment by OndrejSedivy** [comment]
works fine now
