### ISSUE TITLE
File Watcher for Prebuilt Pipelines or other bookmarks does not trigger row update when file re-appears on disk

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/SIMPL#89]
Start a DREAM.3D session with a bookmark that is missing. Then on the file system put the bookmark back in the proper spot. In the Bookmarks Widget the row is RED and should update to normal color but does not.

It will work if the bookmark is available on start and then the user deletes the bookmark manually through Windows Explorer or macOS Finder.

**Comment by mmarineBlueQuartz** [comment]
QFileSystemWatcher cannot add paths that do not exist.  Without creating and promptly deleting any missing file, the path will not be watched for changes.
